# Generated by Django 3.2 on 2021-04-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='crypto')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cryptocurrencies',
                'verbose_name_plural': 'Cryptocurrencies',
            },
        ),
    ]
