# Generated by Django 3.2 on 2021-04-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptocurrencies', '0003_alter_crypto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='image',
            field=models.ImageField(blank=True, default='crypto/default.jpg', upload_to='crypto'),
        ),
    ]
